// AddExercises
// exercisesShouldRemainedCheckedAndCanBeAddedAfterRotating
// shouldKeepFilterAfterRotating

// EditRoutine
// shouldShowDiscardChangesDialogIfModifiedThenRotatedThenPressBack
// shouldSaveNewOrderIfChangedOrderThenRotated
// shouldKeepNewExercisesAddedAfterAddingThenRotating

// Workout
// shouldKeepRepsAndWeightAfterRotating
// shouldKeepSetsAndSaveAfterRotating
// shouldShowDiscardChangesDialogIfAddSetThenRotatedThenPressBack